-- ============================================================================
-- DISASTER RECOVERY MIGRATION — multi-tenant saam-s-store backend
-- ============================================================================
-- Run this entire file, top to bottom, in a brand-new Supabase project's
-- SQL Editor to recreate the full structure (tables, RLS policies, RPC
-- functions, storage bucket + policies) used by every client site sharing
-- this backend. Recreates STRUCTURE ONLY — no tenant/admin/product/order
-- data. All tables come back empty; re-seed tenants and store_admins
-- yourself (see the commented example at the bottom).
--
-- Generated by introspecting the live project (siwosrjmbrgoautfmzfy) on
-- 2026-07-25 — reflects the actual current schema/policies/functions,
-- not a hand-remembered version. If you make further schema changes going
-- forward, regenerate this file so it doesn't drift from reality.
--
-- AFTER RUNNING:
--   1. Create a storage bucket named "images" (Dashboard → Storage) — the
--      bucket itself can't be created via plain SQL, only policies can.
--      Actually handled below via storage.buckets insert, but if that
--      fails on your Supabase version, create it manually (Public = ON)
--      before re-running the storage policy section.
--   2. Update EVERY client Vercel project's NEXT_PUBLIC_SUPABASE_URL and
--      NEXT_PUBLIC_SUPABASE_ANON_KEY to this new project's values.
--   3. Re-seed tenants + store_admins for every client (see bottom).
--   4. Re-create each client's admin user in Authentication → Users.
--   5. Re-upload product/category/hero images per client (originals are
--      lost unless you kept a separate backup of the storage bucket).
-- ============================================================================


-- ============================================================================
-- STORAGE BUCKET
-- ============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- TABLES
-- ============================================================================

CREATE TABLE tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE store_admins (
  email TEXT PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tenant_id UUID NOT NULL REFERENCES tenants(id)
);

CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  sale_price DECIMAL(10,2),
  category_id INTEGER REFERENCES categories(id),
  stock INTEGER DEFAULT 0,
  is_featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tenant_id UUID NOT NULL REFERENCES tenants(id)
);

CREATE TABLE product_images (
  id SERIAL PRIMARY KEY,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tenant_id UUID NOT NULL REFERENCES tenants(id)
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  address VARCHAR(500) NOT NULL,
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country VARCHAR(255) DEFAULT 'United States',
  payment_method VARCHAR(50) NOT NULL,
  order_items JSONB NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tenant_id UUID NOT NULL REFERENCES tenants(id)
);

CREATE TABLE contacts (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  subject VARCHAR(255),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tenant_id UUID NOT NULL REFERENCES tenants(id)
);

CREATE TABLE hero_slides (
  id SERIAL PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES tenants(id),
  title TEXT NOT NULL,
  subtitle TEXT,
  description TEXT,
  cta_text TEXT DEFAULT 'SHOP NOW',
  cta_link TEXT DEFAULT '/shop',
  image_url TEXT,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE addresses (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  label VARCHAR(100),
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  address VARCHAR(500) NOT NULL,
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country VARCHAR(255) DEFAULT 'United States',
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE profiles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id),
  full_name VARCHAR(255),
  phone VARCHAR(50),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE wishlist_items (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);


-- ============================================================================
-- ENABLE RLS
-- ============================================================================

ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE hero_slides ENABLE ROW LEVEL SECURITY;
ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishlist_items ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- RLS POLICIES — CATEGORIES
-- ============================================================================

CREATE POLICY "Enable read access for all users" ON categories FOR SELECT TO public USING (true);

CREATE POLICY "Tenant admin insert categories" ON categories FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = categories.tenant_id));
CREATE POLICY "Tenant admin update categories" ON categories FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = categories.tenant_id));
CREATE POLICY "Tenant admin delete categories" ON categories FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = categories.tenant_id));


-- ============================================================================
-- RLS POLICIES — PRODUCTS
-- ============================================================================

CREATE POLICY "Enable read access for all users" ON products FOR SELECT TO public USING (true);

CREATE POLICY "Tenant admin insert products" ON products FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = products.tenant_id));
CREATE POLICY "Tenant admin update products" ON products FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = products.tenant_id));
CREATE POLICY "Tenant admin delete products" ON products FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = products.tenant_id));


-- ============================================================================
-- RLS POLICIES — PRODUCT_IMAGES
-- ============================================================================

CREATE POLICY "Allow public read access" ON product_images FOR SELECT TO public USING (true);

CREATE POLICY "Tenant admin insert images" ON product_images FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = product_images.tenant_id));
CREATE POLICY "Tenant admin delete images" ON product_images FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = product_images.tenant_id));


-- ============================================================================
-- RLS POLICIES — ORDERS
-- Guest order lookups go exclusively through get_order_by_id_and_email()
-- (SECURITY DEFINER below) — no open "read any order" policy exists here.
-- ============================================================================

CREATE POLICY "Allow insert for all" ON orders FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Users can view their own orders" ON orders FOR SELECT TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Tenant admin view all orders" ON orders FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = orders.tenant_id));
CREATE POLICY "Tenant admin update orders" ON orders FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = orders.tenant_id));


-- ============================================================================
-- RLS POLICIES — CONTACTS
-- ============================================================================

CREATE POLICY "Allow insert for all" ON contacts FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Tenant admin read messages" ON contacts FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = contacts.tenant_id));
CREATE POLICY "Tenant admin delete messages" ON contacts FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = contacts.tenant_id));


-- ============================================================================
-- RLS POLICIES — HERO_SLIDES
-- ============================================================================

CREATE POLICY "Enable read access for all users" ON hero_slides FOR SELECT TO public USING (true);

CREATE POLICY "Tenant admin insert hero_slides" ON hero_slides FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = hero_slides.tenant_id));
CREATE POLICY "Tenant admin update hero_slides" ON hero_slides FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = hero_slides.tenant_id));
CREATE POLICY "Tenant admin delete hero_slides" ON hero_slides FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM store_admins sa WHERE sa.email = auth.jwt() ->> 'email' AND sa.tenant_id = hero_slides.tenant_id));


-- ============================================================================
-- RLS POLICIES — STORE_ADMINS
-- Only used internally by the EXISTS checks above; each admin can only see
-- their own row (needed so those subqueries are allowed to run at all).
-- ============================================================================

CREATE POLICY "Authenticated can check their own admin row" ON store_admins FOR SELECT TO authenticated
USING (email = auth.jwt() ->> 'email');


-- ============================================================================
-- RLS POLICIES — ADDRESSES / PROFILES / WISHLIST_ITEMS (customer-owned)
-- ============================================================================

CREATE POLICY "Users can view their own addresses" ON addresses FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own addresses" ON addresses FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own addresses" ON addresses FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own addresses" ON addresses FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own wishlist" ON wishlist_items FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert into their own wishlist" ON wishlist_items FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete from their own wishlist" ON wishlist_items FOR DELETE TO authenticated USING (auth.uid() = user_id);


-- ============================================================================
-- RPC FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION get_price_range(p_tenant_id uuid)
RETURNS TABLE (min_price numeric, max_price numeric)
LANGUAGE sql STABLE AS $$
  SELECT MIN(price), MAX(price) FROM products WHERE tenant_id = p_tenant_id;
$$;
GRANT EXECUTE ON FUNCTION get_price_range(uuid) TO anon, authenticated;

CREATE OR REPLACE FUNCTION get_order_by_id_and_email(order_id bigint, order_email text, p_tenant_id uuid)
RETURNS SETOF orders
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT * FROM orders WHERE id = order_id AND email = order_email AND tenant_id = p_tenant_id;
$$;
GRANT EXECUTE ON FUNCTION get_order_by_id_and_email(bigint, text, uuid) TO anon, authenticated;

CREATE OR REPLACE FUNCTION create_order(order_data jsonb)
RETURNS orders
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  new_order orders;
BEGIN
  INSERT INTO orders (
    first_name, last_name, email, phone, address, city, state,
    postal_code, country, payment_method, order_items, subtotal,
    total, status, user_id, tenant_id
  )
  VALUES (
    order_data->>'first_name',
    order_data->>'last_name',
    order_data->>'email',
    order_data->>'phone',
    order_data->>'address',
    order_data->>'city',
    order_data->>'state',
    order_data->>'postal_code',
    order_data->>'country',
    order_data->>'payment_method',
    (order_data->'order_items')::jsonb,
    (order_data->>'subtotal')::numeric,
    (order_data->>'total')::numeric,
    'pending',
    NULLIF(order_data->>'user_id', '')::uuid,
    (order_data->>'tenant_id')::uuid
  )
  RETURNING * INTO new_order;
  RETURN new_order;
END;
$$;
GRANT EXECUTE ON FUNCTION create_order(jsonb) TO anon, authenticated;


-- ============================================================================
-- STORAGE POLICIES — tenant-scoped folder access ({tenant_id}/... prefix)
-- ============================================================================

CREATE POLICY "Allow public read access" ON storage.objects FOR SELECT TO public
USING (bucket_id = 'images');

CREATE POLICY "Tenant admin insert own folder" ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'images'
  AND EXISTS (
    SELECT 1 FROM store_admins sa
    WHERE sa.email = auth.jwt() ->> 'email'
      AND sa.tenant_id::text = (storage.foldername(name))[1]
  )
);

CREATE POLICY "Tenant admin delete own folder" ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id = 'images'
  AND EXISTS (
    SELECT 1 FROM store_admins sa
    WHERE sa.email = auth.jwt() ->> 'email'
      AND sa.tenant_id::text = (storage.foldername(name))[1]
  )
);


-- ============================================================================
-- DONE. Structure is back. Everything below is empty — re-seed per client.
-- ============================================================================
-- Example for restoring one client (repeat per client, then recreate their
-- admin user in Authentication → Users with the matching email):
--
-- WITH new_tenant AS (
--   INSERT INTO tenants (slug, name) VALUES ('client1', 'Oman and Alam')
--   RETURNING id
-- )
-- INSERT INTO store_admins (email, tenant_id)
-- SELECT 'testemail@gmail.com', id FROM new_tenant;
-- ============================================================================
